"""Cross-namespace resolution (firm kinds) across the three knowledge books.

Reads /tmp/cross_groups_firmes.json (generated by gen_cross_groups.py filtered to
tool/framework/mcp/agent kinds) and merges each group with ApplyMergeUseCase:
soft-delete merged_into + re-point MENTIONS/RELATED + fold aliases + ledger
chained with approver human:gonzalo. Evidence is cross-namespace (band EXACT,
cross_namespace=True, per-pair anchor/candidate namespaces derived from the ids).

Usage (AGENTS.md §7.2: backup -> dry-run -> aprobación -> apply):
  uv run python resolve_cross_namespace.py --dry-run   # read-only validation
  uv run python resolve_cross_namespace.py --apply     # apply merges, ledger seq 303+
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from typing import Any

from neo4j import GraphDatabase

from book_graph_rag.application.resolve_entities_use_case import MergeGroup
from book_graph_rag.config import Settings
from book_graph_rag.domain.models import EntityType
from book_graph_rag.domain.resolution_models import (
    ConfidenceBand,
    ResolutionEvidence,
    S0NormalizedForm,
)
from book_graph_rag.infrastructure.resolution_wiring import build_apply_merge_use_case

DEFAULT_GROUPS_JSON = "/tmp/cross_groups_firmes.json"

GROUPS_JSON = os.environ.get("CROSS_GROUPS_JSON", DEFAULT_GROUPS_JSON)


def _ns(entity_id: str) -> str:
    return ":".join(entity_id.split(":")[:2])


def build_group(entry: dict[str, Any]) -> MergeGroup:
    canonical_id: str = entry["canonical"]
    dup_ids: list[str] = entry["candidates"]
    kind: EntityType = entry["kind"]

    def _s0(entity_id: str) -> S0NormalizedForm:
        raw = entity_id.rsplit(":", 1)[-1].replace("-", " ")
        return S0NormalizedForm(
            original=raw,
            nfkc=raw,
            casefold=raw.lower(),
            compact="".join(raw.lower().split()),
            tokens=tuple(raw.lower().split()),
        )

    anchor_ns = _ns(canonical_id)
    evidence = [
        ResolutionEvidence(
            anchor_id=canonical_id,
            candidate_id=d,
            anchor_type=kind,
            candidate_type=kind,
            anchor_namespace=anchor_ns,
            candidate_namespace=_ns(d),
            anchor_normalized=_s0(canonical_id),
            candidate_normalized=_s0(d),
            s0_matched_field="id",
            band=ConfidenceBand.EXACT,
            cross_namespace=True,
            cross_type=False,
            composite_score=1.0,
        )
        for d in dup_ids
    ]
    return MergeGroup(
        canonical_id=canonical_id,
        duplicate_ids=dup_ids,
        band=ConfidenceBand.EXACT,
        evidence=evidence,
    )


def dry_run() -> int:
    with open(GROUPS_JSON, encoding="utf-8") as f:
        groups = json.load(f)
    all_ids = [x["canonical"] for x in groups] + [c for x in groups for c in x["candidates"]]
    settings = Settings.model_validate({})
    driver = GraphDatabase.driver(
        settings.neo4j_uri,
        auth=(settings.neo4j_user, settings.neo4j_password.get_secret_value()),
    )
    try:
        with driver.session() as s:
            rows = list(
                s.run(
                    "MATCH (n:Entity) WHERE n.id IN $ids RETURN n.id AS id, n.merged_into AS mi",
                    ids=all_ids,
                )
            )
    finally:
        driver.close()

    found = {r["id"]: r["mi"] for r in rows}
    missing = [i for i in all_ids if i not in found]
    inactive = [i for i in all_ids if found.get(i)]
    n_dups = sum(len(x["candidates"]) for x in groups)

    print(f"groups={len(groups)} canonical={len(groups)} duplicates={n_dups}")
    print(
        f"ids_checked={len(all_ids)} found={len(found)} "
        f"missing={len(missing)} inactive={len(inactive)}"
    )
    for label, lst in (("MISSING", missing), ("INACTIVE", inactive)):
        for i in lst:
            print(f"{label}: {i}")
    if missing or inactive:
        print("DRY_RUN BLOCKED")
        return 1
    print("DRY_RUN OK - listo para --apply")
    return 0


async def apply() -> int:
    with open(GROUPS_JSON, encoding="utf-8") as f:
        groups = json.load(f)
    settings = Settings.model_validate({})
    use_case, closables = await build_apply_merge_use_case(settings)
    results: list[tuple[str, int, int]] = []
    try:
        for entry in groups:
            group = build_group(entry)
            res = await use_case.apply(group, approver="human:gonzalo")
            results.append((group.canonical_id, res.seq, len(group.duplicate_ids)))
    finally:
        for closer in closables:
            await closer.close()
    for cid, seq, ndup in results:
        print(f"MERGE_OK seq={seq} canon={cid} dups={ndup}")
    print(f"APPLY_DONE groups={len(results)}")
    return 0


async def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--dry-run", action="store_true", help="read-only validation")
    mode.add_argument("--apply", action="store_true", help="apply merges (ledger)")
    args = parser.parse_args()
    if args.dry_run:
        return dry_run()
    return await apply()


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
