"""Property: resolution policy matrix is invariant under arbitrary evidence.

The binding band-to-action matrix (engram 1165) must hold for every possible
anchor/candidate pair generated by Hypothesis: cross-type is a hard NO_MERGE
boundary, cross-namespace is a hard QUARANTINE boundary, and same-type
same-namespace pairs follow the exact/high/medium/low routing.

These tests are pure: they construct ``ResolutionEvidence`` directly and call
``decide()`` with no Neo4j, no testcontainers, and no real model.
"""

from __future__ import annotations

from datetime import UTC, datetime

from hypothesis import given, settings
from hypothesis import strategies as st

from book_graph_rag.domain.models import EntityType
from book_graph_rag.domain.resolution_models import (
    ConfidenceBand,
    ResolutionEvidence,
    S0NormalizedForm,
    S1EmbeddingSignal,
    S2TypeGateResult,
    S3ContextSignals,
)
from book_graph_rag.domain.resolution_policy import MergeAction, decide
from book_graph_rag.domain.s4_band_assignment import BandThresholds

_ENTITY_TYPES: list[EntityType] = [
    "pattern",
    "agent",
    "component",
    "concept",
    "tool",
    "framework",
    "mcp",
    "llmops",
    "risk",
]

_NAMESPACE_STRATEGY = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N")),
    min_size=1,
    max_size=16,
)

_S0_NORM = S0NormalizedForm(
    original="Anchor",
    nfkc="Anchor",
    casefold="anchor",
    compact="anchor",
    tokens=("anchor",),
)

_CAND_NORM = S0NormalizedForm(
    original="Candidate",
    nfkc="Candidate",
    casefold="candidate",
    compact="candidate",
    tokens=("candidate",),
)


@st.composite
def _evidence_strategy(draw: st.DrawFn) -> ResolutionEvidence:
    """Generate arbitrary resolution evidence while controlling the cross flags."""
    band = draw(st.sampled_from(ConfidenceBand))
    cross_type = draw(st.booleans())
    cross_namespace = draw(st.booleans())

    if cross_type:
        anchor_type, candidate_type = draw(
            st.tuples(
                st.sampled_from(_ENTITY_TYPES),
                st.sampled_from(_ENTITY_TYPES),
            ).filter(lambda pair: pair[0] != pair[1])
        )
    else:
        entity_type = draw(st.sampled_from(_ENTITY_TYPES))
        anchor_type = candidate_type = entity_type

    if cross_namespace:
        anchor_namespace, candidate_namespace = draw(
            st.tuples(_NAMESPACE_STRATEGY, _NAMESPACE_STRATEGY).filter(
                lambda pair: pair[0] != pair[1]
            )
        )
    else:
        namespace = draw(_NAMESPACE_STRATEGY)
        anchor_namespace = candidate_namespace = namespace

    s0_matched_field = (
        draw(st.sampled_from(["id", "canonical", "alias"]))
        if band == ConfidenceBand.EXACT
        else "none"
    )

    cosine = draw(st.floats(min_value=0.0, max_value=1.0))
    mentions_j = draw(st.floats(min_value=0.0, max_value=1.0))
    related_j = draw(st.floats(min_value=0.0, max_value=1.0))
    description_overlap = draw(st.floats(min_value=0.0, max_value=1.0))
    mentions_union = draw(st.integers(min_value=0, max_value=50))
    mentions_shared = (
        draw(st.integers(min_value=0, max_value=mentions_union))
        if mentions_union > 0
        else 0
    )
    related_union = draw(st.integers(min_value=0, max_value=50))
    related_shared = (
        draw(st.integers(min_value=0, max_value=related_union))
        if related_union > 0
        else 0
    )

    return ResolutionEvidence(
        anchor_id=f"{anchor_namespace}:{anchor_type}:anchor",
        candidate_id=f"{candidate_namespace}:{candidate_type}:candidate",
        anchor_type=anchor_type,
        candidate_type=candidate_type,
        anchor_namespace=anchor_namespace,
        candidate_namespace=candidate_namespace,
        anchor_normalized=_S0_NORM,
        candidate_normalized=_CAND_NORM,
        s0_matched_field=s0_matched_field,  # type: ignore[arg-type]
        s1=S1EmbeddingSignal(
            cosine_similarity=cosine,
            candidate_rank=1,
            input_variant="A",
            model_id="fake",
        ),
        s2=S2TypeGateResult(
            anchor_type=anchor_type,
            candidate_type=candidate_type,
            passed=not cross_type,
            reason="type gate result",
        ),
        s3=S3ContextSignals(
            mentions_jaccard=mentions_j,
            related_jaccard=related_j,
            description_overlap=description_overlap,
            mentions_source_count=mentions_union,
            mentions_shared_count=mentions_shared,
            related_neighbor_count=related_union,
            related_shared_count=related_shared,
            conflict_flag=False,
        ),
        composite_score=(mentions_j + related_j + description_overlap) / 3.0,
        band=band,
        cross_namespace=cross_namespace,
        cross_type=cross_type,
        decided_at=datetime(2024, 1, 1, tzinfo=UTC),
    )


@given(
    evidence=_evidence_strategy(),
    thresholds=st.builds(BandThresholds),
)
@settings(max_examples=200, deadline=None)
def test_resolution_policy_matrix_respects_hard_boundaries_and_bands(
    evidence: ResolutionEvidence,
    thresholds: BandThresholds,
) -> None:
    """Cross-type and cross-namespace are hard boundaries; same-type same-namespace
    follows the band matrix.
    """
    decision = decide(evidence, thresholds)

    if evidence.cross_type:
        assert decision.action == MergeAction.NO_MERGE
        assert evidence.candidate_type != evidence.anchor_type
        return

    if evidence.cross_namespace:
        assert decision.action == MergeAction.QUARANTINE
        return

    if evidence.band == ConfidenceBand.EXACT:
        assert decision.action == MergeAction.AUTO_MERGE
    elif evidence.band in (ConfidenceBand.HIGH, ConfidenceBand.MEDIUM):
        assert decision.action == MergeAction.QUARANTINE
    else:
        assert evidence.band == ConfidenceBand.LOW
        assert decision.action == MergeAction.NO_MERGE


@given(
    evidence=_evidence_strategy().filter(lambda e: e.cross_namespace),
    thresholds=st.builds(BandThresholds),
)
@settings(max_examples=100, deadline=None)
def test_cross_namespace_never_auto_merges(
    evidence: ResolutionEvidence,
    thresholds: BandThresholds,
) -> None:
    """A cross-namespace candidate is never promoted to AUTO_MERGE."""
    decision = decide(evidence, thresholds)
    assert decision.action != MergeAction.AUTO_MERGE
